### PR TITLE
Added SQL Constraints To Database

### PR DESCRIPTION
**Pull request by ASimpleFox**
Added SQL constraints to make sure the insert statements and data is correct (not null for certain statements). Also added constraints for eventually being able to delete users from the database. 

Code is tested on my local machine, please test (if possible) when you review!

### CODE REVIEW

**Review by ElliotSchumacher — CHANGES_REQUESTED** [review]
I ran the new database setup code and there were no errors. I did not check to see if deleting a parent record also deleted a child record. I believe that is still untested.

Issue: 
Our endpoints need the test user's passwords to be hashed. The current insert statements don't create hashed passwords. This causes problems when running endpoint tests. When I tried to delete the `User` table's insert statements, we face issues with other insert statements because they rely on users already existing.

**Comment by ASimpleFox** [comment]
Added deletion parent record (user, based on name, can be based on ID if we want) and tested it. Seems to work on my end, would like another set of testing to be done. Will add delete statements for bookshelves/books in a separate commit 

Regarding issue: 
We can pass in hashed passwords as long as it's as a string and it would still function the same as our current INSERT statements. All we have to do is pass in a hashed string as the password field instead of our sample passwords.

CONSTRAINTS in SQL form a top-down sequence so we have to insert in a certain order, but I think that order's inherent in the front end (first create user, then create bookshelves, then add/remove books), so insert order shouldn't be a problem for the MVP unless... they made the front-end really wonky...

**Review by ASimpleFox — COMMENTED** [review]
These changes look fine, think it was just data reordering?

**Comment by ASimpleFox** [comment]
I'm assuming we don't want to delete a book's data when someone wants to remove it from their bookshelves, so that constraint issue is fixed. Requesting check please, let me know if there are any other concerns.

Hashed passwords aren't currently accounted, I don't think we need to unless the password isn't a string format (none of the delete statements are based on password)

**Review by ElliotSchumacher — APPROVED** [review]
Tested and Approved

**Pull request merged**
