### PR TITLE
Refactor Api

### PR DESCRIPTION
**Pull request by s-lakshmanansi**
I just refactored the api. Make sure I got everything lol...

Note that to actually run it, you will need to create a file called ".env" in the backend folder. This will contain all of the important info that the server needs to run.

Heres what my .env file has in it: (feel free to change the ports to wherever you are running it)
```
DB_URL=localhost
DB_PORT=8889
DB_USERNAME=admin
DB_PASSWORD=root
DB_NAME=huskyreads

PORT=8000
```

Note that at you should NEVER push the .env file to git (thats why it is in the gitignore). For the future, this file will be used to contain secret keys, etc for hashing passwords and the like.

Also, if everything passes, we can probably create another pull request to delete the api folder or something.

### CODE REVIEW

**Comment by ASimpleFox** [comment]
Check the deepscan issues + prolly wait on merging til we finish with Nicholas's endpoint/branch

**Review by ElliotSchumacher — CHANGES_REQUESTED** [review]
The `/bookshelves/add` endpoint is not working for my tests. When I make a POST request to `localhost:8000/bookshelves/add`, a response is sent back with the message `Cannot POST /bookshelves/add`. This is the only endpoint currently failing my tests. Please take a look at this and I'll rerun my tests afterwards.

**Comment by s-lakshmanansi** [comment]
> 
> 
> The `/bookshelves/add` endpoint is not working for my tests. When I make a POST request to `localhost:8000/bookshelves/add`, a response is sent back with the message `Cannot POST /bookshelves/add`. This is the only endpoint currently failing my tests. Please take a look at this and I'll rerun my tests afterwards.

**Comment by s-lakshmanansi** [comment]
whoops

**Review by ElliotSchumacher — APPROVED** [review]
All tests pass and I like the new folder structure.

**Pull request merged**
