### PR TITLE
Auth cookies

### PR DESCRIPTION
**Pull request by s-lakshmanansi**
Things changed:
1. Added password hashing through the use of bcrypt
2. Added cookies for both authentication and color_scheme
3. Fixed color_scheme endpoint to update color_scheme in database correctly
4. Added ways to access and delete cookies (as cookies are encrypted)
5. Updated API documentation to reflect changes to endpoints

IMPORTANT: New .env file!!!!
```
# Database
DB_URL=db
DB_PORT=3306
DB_USERNAME=root
DB_PASSWORD=root
DB_NAME=huskyreads

# Backend
PORT=8000

# Bcrypt keys
SALT=10

# JWT keys
JWT_KEY=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzMDk4NDg4NiwiaWF0IjoxNjMwOTg0ODg2fQ.i83U3IYDSbMDmysEMmJAtEoy9KAlrsXX1EhakdSVjgQ

```

Things to note:
1. Cookies have not been made "secure" and "http only" because we are still in development. Once we go to production, all cookies must be made "secure" and "http only" (as simple as adding a few flags to each cookie).
2. We need to tell the front-end about our cookie strategy (like how to access values, where cookies are created/deleted, etc.)
3. Lemme know if you guys have any questions lol...ik its a lot (I can make a short presentation about how our cookies work if you want)
4. Elliot reminded me-- Passwords are now hashed, so test users will need to be added manually using the signup endpoint.

### CODE REVIEW

**Review by ASimpleFox — COMMENTED** [review]
Looks good, has this code been tested at all? If it has and it works, it should be fine, otherwise we should probably do some testing before merging it with master

**Comment by s-lakshmanansi** [comment]
> 
> 
> Looks good, has this code been tested at all? If it has and it works, it should be fine, otherwise we should probably do some testing before merging it with master

Its been tested theoretically with axios, but there is no way to be sure if it works on the front-end side until they start using it.

**Review by ASimpleFox — DISMISSED** [review]
Seems good to me then, I'll approve and we can test when front-end gets their stuff together for the MVP. Going to wait on Elliot to give this a once-over before merging with master

**Review by ElliotSchumacher — APPROVED** [review]
I ran all old tests and they all pass. Like Sid, I'm not sure how to test the cookies before the front-end team implements them so I haven't tested them yet. 

I do think that it is important for people to know that all the passwords in the database are hashed and that the current 'database.sql' file has insert statements that create user records with un-hashed passwords. This means that anyone that uses the 'login' endpoint while they have un-hashed passwords in the database will get an error.

**Pull request merged**
